even more debugging

diff --git a/.github/workflows/ci-workflow.yml b/.github/workflows/ci-workflow.yml
--- a/.github/workflows/ci-workflow.yml
+++ b/.github/workflows/ci-workflow.yml
@@ -453,9 +453,13 @@ jobs:
           download_vulkan_installer ${VULKAN_SDK_PLATFORM}
           unpack_vulkan_installer ${VULKAN_SDK_PLATFORM}
 
-      - name: Debug check env vars
+      - name: Debug check
+        shell: bash
         run: |
-          echo $VULKAN_SDK
+          echo "VULKAN_SDK=$VULKAN_SDK"
+          ls -la "$VULKAN_SDK"
+          ls -la "$VULKAN_SDK/Include" || echo "Include not found"
+          ls -la "$VULKAN_SDK/Lib" || echo "Lib not found"
 
       - name: Update Environment Variables
         run: |
